# Generated by Django 4.2.2 on 2024-05-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='departamento',
            new_name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default=0, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
